require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DodesusController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dodesu. As you add validations to Dodesu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DodesusController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dodesus as @dodesus" do
      dodesu = Dodesu.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dodesus)).to eq([dodesu])
    end
  end

  describe "GET show" do
    it "assigns the requested dodesu as @dodesu" do
      dodesu = Dodesu.create! valid_attributes
      get :show, {:id => dodesu.to_param}, valid_session
      expect(assigns(:dodesu)).to eq(dodesu)
    end
  end

  describe "GET new" do
    it "assigns a new dodesu as @dodesu" do
      get :new, {}, valid_session
      expect(assigns(:dodesu)).to be_a_new(Dodesu)
    end
  end

  describe "GET edit" do
    it "assigns the requested dodesu as @dodesu" do
      dodesu = Dodesu.create! valid_attributes
      get :edit, {:id => dodesu.to_param}, valid_session
      expect(assigns(:dodesu)).to eq(dodesu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dodesu" do
        expect {
          post :create, {:dodesu => valid_attributes}, valid_session
        }.to change(Dodesu, :count).by(1)
      end

      it "assigns a newly created dodesu as @dodesu" do
        post :create, {:dodesu => valid_attributes}, valid_session
        expect(assigns(:dodesu)).to be_a(Dodesu)
        expect(assigns(:dodesu)).to be_persisted
      end

      it "redirects to the created dodesu" do
        post :create, {:dodesu => valid_attributes}, valid_session
        expect(response).to redirect_to(Dodesu.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dodesu as @dodesu" do
        post :create, {:dodesu => invalid_attributes}, valid_session
        expect(assigns(:dodesu)).to be_a_new(Dodesu)
      end

      it "re-renders the 'new' template" do
        post :create, {:dodesu => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dodesu" do
        dodesu = Dodesu.create! valid_attributes
        put :update, {:id => dodesu.to_param, :dodesu => new_attributes}, valid_session
        dodesu.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dodesu as @dodesu" do
        dodesu = Dodesu.create! valid_attributes
        put :update, {:id => dodesu.to_param, :dodesu => valid_attributes}, valid_session
        expect(assigns(:dodesu)).to eq(dodesu)
      end

      it "redirects to the dodesu" do
        dodesu = Dodesu.create! valid_attributes
        put :update, {:id => dodesu.to_param, :dodesu => valid_attributes}, valid_session
        expect(response).to redirect_to(dodesu)
      end
    end

    describe "with invalid params" do
      it "assigns the dodesu as @dodesu" do
        dodesu = Dodesu.create! valid_attributes
        put :update, {:id => dodesu.to_param, :dodesu => invalid_attributes}, valid_session
        expect(assigns(:dodesu)).to eq(dodesu)
      end

      it "re-renders the 'edit' template" do
        dodesu = Dodesu.create! valid_attributes
        put :update, {:id => dodesu.to_param, :dodesu => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dodesu" do
      dodesu = Dodesu.create! valid_attributes
      expect {
        delete :destroy, {:id => dodesu.to_param}, valid_session
      }.to change(Dodesu, :count).by(-1)
    end

    it "redirects to the dodesus list" do
      dodesu = Dodesu.create! valid_attributes
      delete :destroy, {:id => dodesu.to_param}, valid_session
      expect(response).to redirect_to(dodesus_url)
    end
  end

end
